import '@styles/globals.css'
import '@styles/prism-night-theme.css'
import type { Metadata } from 'next'
import { Roboto, Poppins, Cousine } from 'next/font/google'

import { i18n, Locale } from '@root/i18n-config'
import { getDictionary } from '@root/get-dictionary'
import { cn } from '@lib/utils'
import { Layout } from '@components/Surfaces'
import { LocaleProvider } from '@root/src/provider/LocaleProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const roboto = Roboto({
  weight: ['400', '500', '700'],
  style: 'normal',
  subsets: ['latin'],
  variable: '--font-roboto'

})

const poppins = Poppins({
  weight: ['400', '500', '700'],
  style: 'normal',
  subsets: ['latin'],
  variable: '--font-poppins'

})

const cousine = Cousine({
  weight: ['400', '700'],
  style: 'normal',
  subsets: ['latin'],
  variable: '--font-cousine'
})

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode
  params: {
    lang: Locale
  }
}>) {
  const { lang } = await params
  const dictionary = await getDictionary(lang)

  return (
        <html lang="en">
          <LocaleProvider dictionary={dictionary} lng={lang}>
              <body suppressHydrationWarning className={cn(
                'min-h-screen bg-white dark:bg-black',
                poppins?.variable,
                roboto?.variable,
                cousine?.variable
              )}>
              <Layout locale={lang}>
              {children}
              </Layout>
              </body>
          </LocaleProvider>
        </html>
  )
}
