import "@styles/globals.css";
import "@styles/prism-night-theme.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import "@fontsource/poppins/400.css";
import "@fontsource/poppins/500.css";
import "@fontsource/poppins/700.css";
import "@fontsource/cousine/400.css";
import "@fontsource/cousine/700.css";
import type { Metadata } from "next";
import React from "react";

import { Layout } from "@components/Surfaces";
import { cn } from "@lib/utils";
import { getDictionary } from "@root/get-dictionary";
import { i18n, Locale } from "@root/i18n-config";
import { LocaleProvider } from "@root/src/provider/LocaleProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode
  params: {
    lang: Locale
  }
}>) {
  const { lang } = await params;
  const dictionary = await getDictionary(lang);

  return (
    <html lang="en">
      <LocaleProvider dictionary={dictionary} lng={lang}>
        <body suppressHydrationWarning className={cn(
          "min-h-screen bg-white dark:bg-black"
        )}>
          <Layout locale={lang}>
            {children}
          </Layout>
        </body>
      </LocaleProvider>
    </html>
  );
}
