import "@styles/globals.css";
import "@styles/prism-night-theme.css";
import type { Metadata } from "next";
// Temporarily commented out Google Fonts due to network connectivity issues during build
// import { Roboto, Poppins, Cousine } from "next/font/google";
import  React from "react";

import { cn } from "@lib/utils";
import { getDictionary } from "@root/get-dictionary";
import { i18n, Locale } from "@root/i18n-config";
import { LocaleProvider } from "@root/src/provider/LocaleProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

// Temporarily use system fonts as fallback
// const roboto = Roboto({
//   weight: [ "400", "500", "700" ],
//   style: "normal",
//   subsets: [ "latin" ],
//   variable: "--font-roboto",
//   display: "swap",
//   adjustFontFallback: false,
//   preload: false
// });

// const poppins = Poppins({
//   weight: [ "400", "500", "700" ],
//   style: "normal",
//   subsets: [ "latin" ],
//   variable: "--font-poppins",
//   display: "swap",
//   adjustFontFallback: false,
//   preload: false
// });

// const cousine = Cousine({
//   weight: [ "400", "700" ],
//   style: "normal",
//   subsets: [ "latin" ],
//   variable: "--font-cousine",
//   display: "swap",
//   adjustFontFallback: false,
//   preload: false
// });

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode
  params: {
    lang: Locale
  }
}>) {
  const { lang } = await params;
  const dictionary = await getDictionary(lang);

  return (
    <html lang="en">
      <LocaleProvider dictionary={dictionary} lng={lang}>
        <body suppressHydrationWarning className={cn(
          "min-h-screen bg-white dark:bg-black"
          // Temporarily removed font variables until Google Fonts connectivity is restored
          // poppins?.variable,
          // roboto?.variable,
          // cousine?.variable
        )}>
          {children}
        </body>
      </LocaleProvider>
    </html>
  );
}
